name: Address sanitizer

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**.swift'
      - 'Package.resolved'
      - '**.c'
      - '**.h'
  pull_request:
    branches: [ main ]
    paths:
      - '**.swift'
      - 'Package.resolved'
      - '**.c'
      - '**.h'

jobs:
  address-sanitizer:
    strategy:
      fail-fast: false
      matrix:
        os: [[swift-latest, ubuntu-latest, self-hosted], [swift-nightly, ubuntu-latest, self-hosted], [macos-13, self-hosted]]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    steps:
    # Needed otherwise xcode git hangs on checkout
    - name: Wipe gitconfig Mac
      if: ${{ runner.os == 'Macos' }}
      run: |
        echo "" > ~/.gitconfig
        echo "/opt/homebrew/bin:/usr/local/bin" >> $GITHUB_PATH

    - uses: actions/checkout@v3

    - name: Git URL token override
      run: git config --global url."https://ordo-ci:${{ secrets.CI_MACHINE_PAT }}@github.com".insteadOf "https://github.com"

    - name: Swift version
      run: swift --version

    # Required to clean build directory before sanitizer!
    - name: Clean before debug build sanitizier
      run: swift package clean

    - name: Build with address sanitizer
      run: swift build --sanitize=address

    - name: Run address sanitizer
      run: swift test --sanitize=address
      
    - name: Clean before release build sanitizier
      run: swift package clean
      
    - name: Run address sanitizer on release build
      run: swift test --sanitize=address -c release -Xswiftc -enable-testing

    - name: Wipe gitconfig Mac
      if: ${{ runner.os == 'Macos' }}
      run: echo "" > ~/.gitconfig
